import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
import { css } from '@emotion/css'

export default function Home() {
  const [url, setUrl] = useState('')
  const [link, setLink] = useState('')
  const [hash, setHash] = useState('')
  async function post() {
    if (!url || (!url.startsWith('http') && !url.startsWith('https'))){
      console.log('must be a valid url')
      console.log('url ', url)
      return
    }
    setLink('')
    setHash('')
    const response = await axios.post('/api/fetch-html', {
      url
    })
    console.log({ response })
    setHash(response.data.id)
    setLink(response.data.link)
    setUrl('')
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={wrapperStyle}>
        <div className={mainContainerStyle}>
          <h1 className={titleStyle}>
            ARCHIVE FOREVER
          </h1>
          <p className={descriptionStyle}>Archive any webpage, forever.</p>
          <input
            onChange={e => setUrl(e.target.value)}
            placeholder="Archive a web page"
            className={inputStyle}
            value={url}
          />
          {
            !link && (
              <button onClick={post} className={buttonStyle}>Archive</button>
            )
          }
          {
            link && (
              <div className={linkContainerStyle}>
                <a
                  href={link}
                  rel="noopener"
                  target="_blank"
                >
                  <p className={buttonStyle}>
                  View Archived Page
                  </p>
                </a>
                <button
                  onClick={() => {
                    setHash('')
                    setLink('')
                  }}
                  className={viewLinkButton}
                  target="_blank"
                >
                  Archive new page
                </button>
              </div>
            )
          }
          {
            hash && (
              <p>Arweave transactoin hash: <span className={hashStyle}>{hash}</span></p>
            )
          }
        </div>
      </div>
      <footer className={footerStyle}>
        <p className={footerText}>Built with &nbsp;<a rel="noopener" href="https://www.arweave.org/" target="_blank">Arweave</a>
        &nbsp; and &nbsp;
        <a rel="noopener" target="_blank" href="https://bundlr.network/">Bundlr</a></p>
      </footer>
    </div>
  )
}

const titleStyle = css`
  margin-bottom: 0px;
  font-size: 64px;
  font-weight: 800;
  letter-spacing: 5px;
  text-align: center;
  @media (max-width: 720px) {
    font-size: 50px;
  }
  @media (max-width: 520px) {
    font-size: 40px;
  }
  @media (max-width: 420px) {
    font-size: 30px;
  }
`

const inputStyle = css`
  width: 600px;
  border-radius: 30px;
  border: none;
  outline: none;
  padding: 8px 20px;
  height: 42px;
  font-size: 16px;
  @media (max-width: 720px) {
    width: 100%;
  }
`

const buttonStyle = css`
  height: 36px;
  font-size: 16px;
  padding: 0px 35px;
  background-color: #838383;
  border: none;
  outline: none;
  cursor: pointer;
  border-radius: 2px;
  transition: all .35s;
  display: flex;
  align-items: center;
  margin: 0;
  &:hover {
    background-color: #707070;
  }
  @media (max-width: 720px) {
    margin-top: 0px;
  }
`

const viewLinkButton = css`
  ${buttonStyle};
  margin-left: 12px;
  background-color: white;
  color: black;
  @media (max-width: 720px) {
    margin-left: 0px;
    margin-top: 20px;
  }
`

const linkContainerStyle = css`
  display: flex;
  margin-top: 20px;
  @media (max-width: 720px) {
    flex-direction: column;
  }
`

const mainContainerStyle = css`
  display: flex;
  flex-direction: column;
  align-items: center;
  @media (max-width: 720px) {
    padding: 0px 20px;
  }
`

const hashStyle = css`
  color: #799cff;
  font-size: 14px;
`

const wrapperStyle = css`
  margin-top: 100px;
  min-height: calc(100vh - 160px);
`

const footerStyle = css`
  border-top: 1px solid rgba(255, 255, 255, .2);
  padding: 0px 30px;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 55px;
`

const footerText = css`
  font-size: 14px;
  margin: 0;
  a {
    color: #799cff;
  }
`

const descriptionStyle = css`
  fontSize: 14px;
`